<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * EventLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
