<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * EventHideShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventHideShowRepository extends \Doctrine\ORM\EntityRepository
{


}
