<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * EventChangeSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventChangeSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
