<?php

namespace VisualizationBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GadgetProgressBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GadgetProgressBarRepository extends EntityRepository
{

    public function findForPage($page_id)
    {
        $data = self::findBy(['page' => $page_id]);
        $ret = [];
        foreach ($data as $element) {
            $setRegister = $element->getSetRegisterId();
            if (!empty($setRegister)) {
                $set = $setRegister->getRegisterCurrentData()->getFixedValue();
                $set_percent = ($set - $element->getRangeMin()) / ($element->getRangeMax() - $element->getRangeMin()) * 100;
            } else {
                $set = null;
                $set_percent = null;
            }
            $value = $element->getValueRegisterId()->getRegisterCurrentData()->getFixedValue();
            $value_percent = ($value - $element->getRangeMin()) / ($element->getRangeMax() - $element->getRangeMin()) * 100;
            array_push($ret, ['id' => $element->getId(), 'set' => round($set_percent, 2), 'value' => round($value_percent, 2)]);

        }

        return $ret;
    }
}
