<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * GadgetClockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GadgetClockRepository extends \Doctrine\ORM\EntityRepository
{
}
