<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * GadgetProgressBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GadgetProgressBarRepository extends \Doctrine\ORM\EntityRepository
{

    public function findForPage($page_id)
    {


    }
}
