<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * InputButtonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputButtonRepository extends \Doctrine\ORM\EntityRepository
{
}
