<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * InputNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
