<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * InputRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
