<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * PanelVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelVariableRepository extends \Doctrine\ORM\EntityRepository
{
}
