<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * PanelTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelTextRepository extends \Doctrine\ORM\EntityRepository
{
}
