<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * PanelVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelVariableRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForPage($page_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT rcd.fixedValue as fixed_value, p.id as panel_id FROM BmsConfigurationBundle:Register r'
                . '             JOIN r.registerCurrentData rcd'
                . '             JOIN VisualizationBundle:PanelVariable p'
                . '             WHERE p.source = r.id AND p.page = ' . $page_id . 'ORDER BY r.name')
            ->getResult();
    }
}
