<?php

namespace VisualizationBundle\Entity\Repository;

/**
 * PanelImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelImageRepository extends \Doctrine\ORM\EntityRepository
{
}
