<?php

namespace BmsAlarmBundle\Entity;

/**
 * AlarmHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllOrderByTime(){
        return $this->getEntityManager()
                        ->createQuery('SELECT h FROM BmsAlarmBundle:AlarmHistory AS h ORDER BY h.timeOfOccure DESC')
                        ->getResult();
    }
    
}
