<?php

namespace BmsAlarmBundle\Entity;

/**
 * AlarmHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
