bms:
    resource:
    resource: "@BmsBundle/Resources/config/routing.yml"
    prefix:   /
    
bms_data_analyze:
    resource: "@BmsDataAnalyzeBundle/Resources/config/routing.yml"
    prefix:   /analiza_danych
    
bms_visualization:
    resource: "@BmsVisualizationBundle/Resources/config/routing.yml"
    prefix:   /bms_admin/wizualizacja

bms_configuration:
    resource: "@BmsConfigurationBundle/Resources/config/routing.yml"
    prefix:   /bms_admin/konfiguracja
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"