bms:
    resource: "@BmsBundle/Controller/"
    type: annotation
    prefix:   /
    
bms_admin:
    resource: "@BmsAdminBundle/Controller/"
    type: annotation
    prefix:   /bms_admin

bms_alarm:
    resource: "@BmsAlarmBundle/Controller/"
    type: annotation
    prefix:   /alarm_history

bms_data_analyze:
    resource: "@BmsDataAnalyzeBundle/Controller/"
    type: annotation
    prefix:   /data_analyze
        
bms_visualization:
    resource: "@BmsVisualizationBundle/Controller/"
    type: annotation
    prefix:   /visualization

bms_configuration:
    resource: "@BmsConfigurationBundle/Controller/"
    type: annotation
    prefix:   /configuration
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"