# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:         [ ROLE_USER, ROLE_BMS, ROLE_DATA_ANALYZE, ROLE_CONFIGURATION, ROLE_VISUALIZATION, ROLE_ALARM_HISTORY ]
        ROLE_SUPERADMIN:    ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY,  requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY,  requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY,  requires_channel: https }
        - { path: ^/bms_admin, role: ROLE_ADMIN,  requires_channel: https }
        - { path: ^/data_analyze, role: ROLE_DATA_ANALYZE,  requires_channel: https }
        - { path: ^/configuration, role: ROLE_CONFIGURATION,  requires_channel: https }
        - { path: ^/visualization, role: ROLE_VISUALIZATION,  requires_channel: https }
        - { path: ^/alarm_history, role: ROLE_ALARM_HISTORY,  requires_channel: https }
        - { path: ^/, role: ROLE_BMS,  requires_channel: https }