# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    bms.form.registration:
        class: BmsBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
    
    bmsconfiguration.form.type.task:
        class: BmsConfigurationBundle\Form\BitRegisterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
            
    admin.user:
        class: BmsBundle\Admin\UserAdmin
        arguments: [~, BmsBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Użytkownik }
        calls:
            - [ setTemplate, [edit, AppBundle:PostAdmin:edit.html.twig]]