# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    bms.form.registration:
        class: BmsBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
    
    bmsconfiguration.form.type.task:
        class: BmsConfigurationBundle\Form\BitRegisterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
            
    sonata.admin.user:
        class: BmsBundle\Admin\UserAdmin
        arguments: 
            - ~
            - BmsBundle\Entity\User
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Użytkownik
              
    sonata.admin.hardware:
        class: BmsConfigurationBundle\Admin\HardwareAdmin
        arguments: 
            - ~
            - BmsConfigurationBundle\Entity\Hardware
            - ~
        tags:
            - name: sonata.admin
              manager_type: orm
              label: Połączenie fizyczne 

    sonata.admin.communicationtype:
        class: BmsConfigurationBundle\Admin\CommunicationTypeAdmin
        arguments: 
            - ~
            - BmsConfigurationBundle\Entity\CommunicationType
            - ~
        tags:
            - name:         sonata.admin
              manager_type: orm
              label:        Typ podsieci

    sonata.admin.device:
        class: BmsConfigurationBundle\Admin\DeviceAdmin
        arguments: 
            - ~
            - BmsConfigurationBundle\Entity\Device
            - ~
        tags:
            - name:         sonata.admin
              manager_type: orm
              label:        Urządzenie
    
    sonata.admin.register:
        class: BmsConfigurationBundle\Admin\RegisterAdmin
        arguments: 
            - ~
            - BmsConfigurationBundle\Entity\Register
            - ~
        tags:
            - name:         sonata.admin
              manager_type: orm
              label:        Rejestr
   
    sonata.admin.page:
        class: BmsVisualizationBundle\Admin\PageAdmin
        arguments: 
            - ~
            - BmsVisualizationBundle\Entity\Page
            - ~
        tags:
            - name:         sonata.admin
              manager_type: orm
              label:        Strona
              
    sonata.admin.panel:
        class: BmsVisualizationBundle\Admin\PanelAdmin
        arguments: 
            - ~
            - BmsVisualizationBundle\Entity\Panel
            - ~
        tags:
            - name:         sonata.admin
              manager_type: orm
              label:        Panel
              
    sonata.admin.term:
        class: BmsVisualizationBundle\Admin\TermAdmin
        arguments: 
            - ~
            - BmsVisualizationBundle\Entity\Term
            - ~
        tags:
            - name:         sonata.admin
              manager_type: orm
              label:        Warunek