<?php

namespace BmsVisualizationBundle\Entity;

/**
 * PanelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPanelsForPage($page_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM BmsVisualizationBundle:Panel AS p WHERE p.page = ' . $page_id)
            ->getResult();
    }

    public function findVariablePanelsRegistersForPage($page_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r.name, rcd.fixedValue FROM BmsConfigurationBundle:Register r'
                . '             JOIN r.registerCurrentData rcd'
                . '             JOIN BmsVisualizationBundle:Panel p'
                . '             WHERE p.type = \'variable\' AND p.contentSource LIKE r.name AND p.page = ' . $page_id . 'ORDER BY r.name')
            ->getResult();
    }

    public function getNewPanelName()
    {
        $lastPanel = $this->findLastPanel();
        if (!empty($lastPanel)) {
            return 'panel' . ($lastPanel->getId() + 1);
        } else {
            return 'panel1';
        }
    }

    public function findLastPanel()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('BmsVisualizationBundle:Panel', 'p')
            ->orderBy('p.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
