<?php

namespace BmsVisualizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository {

    public function findAllForPanel($panel_id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT t FROM BmsVisualizationBundle:Term AS t WHERE t.panel = ' . $panel_id)
                        ->getArrayResult();
    }

    public function findAllForPanelAsObject($panel_id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT t FROM BmsVisualizationBundle:Term AS t WHERE t.panel = ' . $panel_id)
                        ->getResult();
    }

    public function findAllAsArray() {
        return $this->getEntityManager()
                        ->createQuery('SELECT t.id, t.name, c.value AS condition_value, c.type AS condition_type, rcd.fixedValue, e.type AS effect_type, e.content AS effect_content, p.id AS panel_id, r.id AS register_id
                                    FROM BmsVisualizationBundle:Term t
                                    JOIN t.register r 
                                    JOIN r.registerCurrentData rcd
                                    JOIN t.condition c
                                    JOIN t.effect e
                                    JOIN t.panel p')->getArrayResult();
    }

    public function findByIdAsArray($term_id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT t.id, t.name, c.value AS condition_value, c.type AS condition_type, rcd.fixedValue, e.type AS effect_type, e.content AS effect_content, p.id AS panel_id, r.id AS register_id, r.name AS register_name
                                    FROM BmsVisualizationBundle:Term t
                                    JOIN t.register r 
                                    JOIN r.registerCurrentData rcd
                                    JOIN t.condition c
                                    JOIN t.effect e
                                    JOIN t.panel p 
                                    WHERE t.id = ' . $term_id)
                        ->getArrayResult();
    }

    public function findTermsForPage($page_id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT t FROM BmsVisualizationBundle:Term t JOIN t.panel p WHERE p.page = ' . $page_id)
                        ->getResult();
    }

}
