<?php

namespace BmsVisualizationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermRepository extends EntityRepository
{
    public function findAllForPanel($panel_id){
        return $this->getEntityManager()
                ->createQuery('SELECT t FROM BmsVisualizationBundle:Term AS t WHERE t.panel = '.$panel_id)
                ->getResult();
    }
}
