<?php

namespace BmsVisualizationBundle\Entity;

/**
 * WidgetBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetBarRepository extends \Doctrine\ORM\EntityRepository {

    public function findWidgetsForPage($page_id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT w FROM BmsVisualizationBundle:WidgetBar w JOIN w.panel p WHERE p.type = \'widget\' AND p.page = ' . $page_id)
                        ->getResult();
    }

}
