<?php

namespace BmsVisualizationBundle\Entity;

/**
 * WidgetBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetBarRepository extends \Doctrine\ORM\EntityRepository {

    public function findWidgetValueRegistersForPage($page_id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT r.id, rcd.fixedValue, p.id as panel_id FROM BmsVisualizationBundle:WidgetBar w '
                                . '             JOIN w.valueRegisterId r '
                                . '             JOIN r.registerCurrentData rcd'
                                . '             JOIN w.panel p'
                                . '             WHERE p.type = \'widget\' AND p.page = ' . $page_id)
                        ->getResult();
    }
    
    public function findWidgetSetRegistersForPage($page_id) {
        return $this->getEntityManager()
                        ->createQuery('SELECT r.id, rcd.fixedValue, p.id as panel_id FROM BmsVisualizationBundle:WidgetBar w '
                                . '             JOIN w.setRegisterId r '
                                . '             JOIN r.registerCurrentData rcd'
                                . '             JOIN w.panel p'
                                . '             WHERE p.type = \'widget\' AND p.page = ' . $page_id)
                        ->getResult();
    }
}
