<?php

namespace BmsVisualizationBundle\Entity;

/**
 * WidgetBarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetBarRepository extends \Doctrine\ORM\EntityRepository
{
}
