<?php

namespace BmsConfigurationBundle\Entity;

/**
 * BitRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BitRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
