<?php

namespace BmsConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommunicationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationTypeRepository extends EntityRepository
{
    public function getActive()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT ct FROM BmsConfigurationBundle:CommunicationType ct'
                . '             JOIN BmsConfigurationBundle:Hardware h'
                . '             WHERE ct.hardware_id = h.id AND h.active = 1')
            ->getResult();
    }

}
