<?php

namespace BmsConfigurationBundle\Entity;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastReadTimes()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT d.id, MIN(rcd.timeOfUpdate) time 
                            FROM BmsConfigurationBundle:Register r 
                            JOIN r.device d 
                            JOIN r.registerCurrentData rcd
                            GROUP BY d.id')
            ->getResult();
    }

    public function getDevicesStatus()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT d.name, d.scanState FROM BmsConfigurationBundle:Device AS d WHERE d.scanState >= 0')
            ->getArrayResult();
    }
}
