<?php

namespace BmsConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArchivatedRegisters() {
        return $this->getEntityManager()
                        ->createQuery('SELECT r.id, r.name, r.description FROM BmsConfigurationBundle:Register AS r WHERE r.archive = 1')
                        ->getResult();
    }
    
    public function getAllOrderByName(){
        return $this->getEntityManager()
                        ->createQuery('SELECT r FROM BmsConfigurationBundle:Register AS r ORDER BY r.name')
                        ->getResult();
    }
    
    public function getAllOrderByAdr($device_id){
        return $this->getEntityManager()
                        ->createQuery('SELECT r FROM BmsConfigurationBundle:Register AS r WHERE r.device =' . $device_id . ' ORDER BY r.registerAddress' )
                        ->getResult();
    }
    
}
