<?php

namespace BmsConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArchivedRegisters()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r.id, r.name, r.description FROM BmsConfigurationBundle:Register AS r WHERE r.archiveRegister = 1')
            ->getResult();
    }

    /**
     * @return array
     */
    public function getAllOrderByName()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM BmsConfigurationBundle:Register AS r ORDER BY r.name')
            ->getResult();
    }

    /**
     * @param $device_id
     * @return array
     */
    public function getAllOrderByAdr($device_id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT r FROM BmsConfigurationBundle:Register AS r WHERE r.device =' . $device_id . ' ORDER BY r.registerAddress')
            ->getResult();
    }

    /**
     * @param $register_name
     * @return \Doctrine\ORM\Query
     */
    public function getFixedValueByRegisterName($register_name)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT rcd.fixedValue FROM BmsConfigurationBundle:Register r 
                                JOIN r.registerCurrentData rcd
                                WHERE r.name LIKE '" . $register_name . "'")
            ->getOneOrNullResult();
    }
}
