services:
#    visualization.example:
#        class: VisualizationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    visualization.twig_extension:
        class: VisualizationBundle\Twig\ColorExtension
        public: false
        tags:
            - { name: twig.extension }

    visualization.form.type.gadgetprogressbar:
            class: VisualizationBundle\Form\GadgetProgressBarType
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: form.type }