bms_configuration_index:
    path:   /
    defaults: { _controller: BmsConfigurationBundle:Default:bmsConfigurationIndex }
    options:
        expose: true
                    
bms_configuration_communication_type:
    path:       /{comm_id}
    defaults: { _controller: BmsConfigurationBundle:Default:configureCommunicationType }
    requirements:
        comm_id:    \d+
    options:
        expose: true
        
bms_configuration_device:
    path:       /{comm_id}/{device_id}
    defaults: { _controller: BmsConfigurationBundle:Default:configureDevice }
    requirements: 
        comm_id:    \d+
        device_id:  \d+
    options:
        expose: true
        
bms_configuration_register:
    path:       /{comm_id}/{device_id}/{register_id}
    defaults:   { _controller: BmsConfigurationBundle:Default:configureRegister }
    requirements: 
        comm_id:        \d+
        device_id:      \d+
        register_id:    \d+
    options:
        expose: true
        
bms_configuration_add_device:
    path:       /{comm_id}/add_device
    defaults: { _controller: BmsConfigurationBundle:Default:addDevice }
    requirements:
        comm_id:    \d+
    options:
        expose: true
        
bms_configuration_add_register:
    path:       /{comm_id}/{device_id}/add_register
    defaults: { _controller: BmsConfigurationBundle:Default:addRegister }
    requirements:
        comm_id:    \d+
        device_id:  \d+
    options:
        expose: true
        
bms_configuration_del_device:
    path:       /{comm_id}/{device_id}/delete
    defaults: { _controller: BmsConfigurationBundle:Default:delDevice }
    requirements:
        comm_id:        \d+
        device_id:      \d+
    
bms_configuration_del_register:
    path:       /{comm_id}/{device_id}/{register_id}/delete
    defaults: { _controller: BmsConfigurationBundle:Default:delRegister }
    requirements:
        comm_id:        \d+
        device_id:      \d+
        register_id:    \d+
        
bms_configuration_del_many_registers:
    path:       /{comm_id}/{device_id}/registers-delete
    defaults: { _controller: BmsConfigurationBundle:Default:delManyRegisters }
    requirements:
        comm_id:        \d+
        device_id:      \d+
        
bms_configuration_del_many_devices:
    path:       /{comm_id}/registers-delete
    defaults: { _controller: BmsConfigurationBundle:Default:delManyDevices }
    requirements:
        comm_id:    \d+
        
bms_configuration_refresh_page:
    path:   /{comm_id}/{device_id}/{register_id}/refresh
    defaults: { _controller: BmsConfigurationBundle:Refresh:refreshPage }
    requirements:
        comm_id:        \d+
        device_id:      \d+
        register_id:    \d+
    options:
        expose: true